/*
389. Find the Difference

You are given two strings s and t.

String t is generated by randomly shuffling string s and then adding
one more letter at a random position.

Return the letter that was added to t.

Example 1:

Input: s = "abcd", t = "abcde"
Output: 'e'

Example 2:

Input: s = "", t = "y"
Output: 'y'

*/

//CODE:

class Solution {

    public char findTheDifference(String s, String t) {

        int xor = 0;

        for (char c : s.toCharArray()) {
            xor ^= c;
        }

        for (char c : t.toCharArray()) {
            xor ^= c;
        }

        return (char) xor;
    }
}